### ISSUE TITLE
IDE independent build configuration

### ISSUE THREAD

**Issue by pocorall** [scouter-project/scouter#3]
Thanks for releasing this awesome project! Congratulations LG CNS for participating open source ecosystem.

I am using IntelliJ IDEA as a primary IDE. Scouter includes eclipse project files in its subprojects. If you set up build configuration (Maven is OK, [sbt](http://www.scala-sbt.org/) is great), there are several advantages:

 * We don't rely on specific IDE
 * Build can be automated
 * Dependency management is much easier

**Comment by scouter-project** [comment]
Thank you for comment, but actually not easy to make build env.
Because Scouter has a some special mechanism. If you extract the scouter.agent.jar then you'll understand what I mean. 
But I know that it is not enough to build Scouter currently. 
Please wait for me (not long time) I'll upload the ant script to build Scouter.

**Comment by scouter-project** [comment]
Now uploaded build scripts

https://github.com/scouter-project/scouter/wiki/Build-Scouter
